services:
  database:
    container_name: database
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.postgres
    ports:
      - "5432:5432"
    restart: always

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - static:/src/app/static
      - media:/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      database:
        condition: service_started
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_started
    restart: on-failure

volumes:
  postgres_data:
  static:
  media:
