name: Build and deploy NGINX

on:
  push:
    paths:
      - 'cicd-pipeline/docker/nginx/index.html'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./cicd-pipeline/docker/nginx
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/nginx:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run NGINX container locally
        run: |
          docker run -d -p 8080:80 --name nginx-container ghcr.io/${{ github.repository_owner }}/nginx:latest

      - name: Verify container is running
        run: |
          docker ps

      - name: Test NGINX locally
        run: |
          curl -f http://localhost:8080 || exit 1

      - name: Clean up
        run: |
          docker stop nginx-container
          docker rm nginx-container

